  CREATE TABLE "SRLP"."PRODUCTS" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE, 
	"BRAND" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"PRICE" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  TABLESPACE "EXAMPLE" ;
  