
  CREATE TABLE "SRLP"."ITEMS" 
   (	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ITEM_DESC" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ITEM_PRICE" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  TABLESPACE "EXAMPLE" ;
 
