
  CREATE TABLE "SRLP"."ITEMS" 
   (	"ITEM_ID" NUMBER NOT NULL ENABLE, 
	"ITEM_NAME" VARCHAR2(250 CHAR) NOT NULL ENABLE, 
	"ITEM_DESC" VARCHAR2(250 CHAR) NOT NULL ENABLE, 
	"ITEM_PRICE" NUMBER NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
 
