//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.11.18 at 10:09:50 AM IST 
//


package org.apache.maven.pom._4_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.apache.maven.pom._4_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.apache.maven.pom._4_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Project.Build }
     * 
     */
    public Project.Build createProjectBuild() {
        return new Project.Build();
    }

    /**
     * Create an instance of {@link Project.Build.Plugins }
     * 
     */
    public Project.Build.Plugins createProjectBuildPlugins() {
        return new Project.Build.Plugins();
    }

    /**
     * Create an instance of {@link Project.Build.Plugins.Plugin }
     * 
     */
    public Project.Build.Plugins.Plugin createProjectBuildPluginsPlugin() {
        return new Project.Build.Plugins.Plugin();
    }

    /**
     * Create an instance of {@link Project.Properties }
     * 
     */
    public Project.Properties createProjectProperties() {
        return new Project.Properties();
    }

    /**
     * Create an instance of {@link Project.Parent }
     * 
     */
    public Project.Parent createProjectParent() {
        return new Project.Parent();
    }

    /**
     * Create an instance of {@link Project.Build.Plugins.Plugin.Configuration }
     * 
     */
    public Project.Build.Plugins.Plugin.Configuration createProjectBuildPluginsPluginConfiguration() {
        return new Project.Build.Plugins.Plugin.Configuration();
    }

}
