DROP TABLE  "SRLP"."PHOTO";

CREATE TABLE "SRLP"."PHOTO" 
   (	"PHOTO_ID" NUMBER NOT NULL ENABLE, 
	"CLOB_DATA" CLOB NOT NULL ENABLE, 
	"BLOB_DATA" BLOB NOT NULL ENABLE, 
	"B_FILE_NAME" VARCHAR2(20) NOT NULL ENABLE,  
	"C_FILE_NAME" VARCHAR2(20) NOT NULL ENABLE,  
	 CONSTRAINT "PHOTO_PK" PRIMARY KEY ("PHOTO_ID")
);
 
