DROP SEQUENCE hibernate_sequence;

CREATE SEQUENCE hibernate_sequence;

DROP TABLE employee;

CREATE TABLE employee (
   ID NUMBER(4) NOT NULL ,
   NAME VARCHAR2(30) NOT NULL,
   joining_date DATE NOT NULL,
   salary NUMBER(10) NOT NULL,
   ssn VARCHAR2(30) NOT NULL,
   PRIMARY KEY (ID)
);

DROP SEQUENCE student_seq;

CREATE SEQUENCE  "SRLP"."STUDENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;

DROP TABLE student;

  CREATE TABLE "SRLP"."STUDENT" 
   (	"SID" NUMBER(19,0) NOT NULL ENABLE, 
	"AGE" NUMBER(10,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"NAME" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;