DROP TABLE "SRLP"."BOOK";

  CREATE TABLE "SRLP"."BOOK" 
   (	"BOOK_ID" NUMBER NOT NULL ENABLE, 
	"ISBN" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"AUTHOR" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"PUBLISHER" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"CITY_PUBLISHED" VARCHAR2(50 CHAR),
	"PUBLISHING_DATE" DATE,
	"EDITION" NUMBER NOT NULL ENABLE, 
	"PRICE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BOOK_PK" PRIMARY KEY ("BOOK_ID")
	);
