INSERT INTO PRODUCT (PROD_ID,NAME,BRAND,VARIANT,PRICE) VALUES (12345,'Triblend Shortsleeve T-Shirt','Apparel','black',15.25);
INSERT INTO PRODUCT (PROD_ID,NAME,BRAND,VARIANT,PRICE) VALUES (67890,'Donut Friday Scented T-Shirt','Apparel','gray',33.85);
INSERT INTO PRODUCT (PROD_ID,NAME,BRAND,VARIANT,PRICE) VALUES (10292,'Kaiser the Cat T-Shirt','Apparel','green',19.1);
INSERT INTO PRODUCT (PROD_ID,NAME,BRAND,VARIANT,PRICE) VALUES (67584,'Organic Cotton Android T-Shirt','Apparel','black',13.5);
INSERT INTO PRODUCT (PROD_ID,NAME,BRAND,VARIANT,PRICE) VALUES (90876,'Maps Biking T-Shirt','Apparel','blue',15.65);
COMMIT;
