  CREATE TABLE "SRLP"."FLIGHT" 
   (	"FLIGHT_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "FLIGHT_PK" PRIMARY KEY ("FLIGHT_ID")
   );
 
  CREATE TABLE "SRLP"."HOTEL" 
   (	"HOTEL_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"TYPE" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "HOTEL_PK" PRIMARY KEY ("HOTEL_ID")
   );
  
  CREATE TABLE "SRLP"."PASSENGER" 
   (	"PASSENGER_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PASSENGER_PK" PRIMARY KEY ("PASSENGER_ID")
   );
  
  CREATE TABLE "SRLP"."FLIGHT_PASSENGER" 
   (	"FLIGHT_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PASSENGER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BOOKED_FROM" DATE, 
	"BOOKED_TO" DATE, 
	 CONSTRAINT "FLIGHT_PASSENGER_FLIGHT_FK1" FOREIGN KEY ("FLIGHT_ID")
	  REFERENCES "SRLP"."FLIGHT" ("FLIGHT_ID") ENABLE, 
	 CONSTRAINT "FLIGHT_PASSENGER_PASSENGE_FK1" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "SRLP"."PASSENGER" ("PASSENGER_ID") ENABLE
   );

  CREATE TABLE "SRLP"."HOTEL_PASSENGER" 
   (	"HOTEL_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PASSENGER_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"BOOKED_FROM" DATE, 
	"BOOKED_TO" DATE, 
	 CONSTRAINT "HOTEL_PASSENGER_HOTEL_FK1" FOREIGN KEY ("HOTEL_ID")
	  REFERENCES "SRLP"."HOTEL" ("HOTEL_ID") ENABLE, 
	 CONSTRAINT "HOTEL_PASSENGER_PASSENGER_FK1" FOREIGN KEY ("PASSENGER_ID")
	  REFERENCES "SRLP"."PASSENGER" ("PASSENGER_ID") ENABLE
   );
 

 
