
  CREATE TABLE "SRLP"."STAFF" 
   (	"STAFF_ID" NUMBER NOT NULL ENABLE, 
	"LNAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"FNAME" VARCHAR2(150 BYTE) NOT NULL ENABLE, 
	"CITY" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"HPHONE" VARCHAR2(50 BYTE) NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EXAMPLE" ;
 
